# Your workflow name.
name: Docker CI/CD pipeline.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v3


### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to Docker hub. # Your custom step name
        uses: docker/login-action@v2 # docker action name (leave it as it is).
        with:
          # Below you must provide variables for your docker hub.

          # Provide Docker hub username from github secrets
          # Provide Docker hub access token from github secrets
          
          username: ${{ secrets.DOCKER_HUB_USERNAME  }}
          
          # Heroku API key associated with provided user's email.
          # Api Key is available under your Heroku account settings.
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN  }}
          
          # Name of the heroku application to which the build is to be sent.
          name: ${{ secrets.DOKCER_APP_NAME }}
          uses: docker/setup-buildx-action@v2

          # name: Build and push
          # uses: docker/build-push-action@v3
          # with:
          # context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/apicicd:latest
          
   
          